version: '3'
services:
    db:
        image: mongo:3.4
    backend:
        image: node:8.1
        volumes: 
            - C:\Users\Marco\Documents\Git\docker-lab\5-compose\backend:/backend
        ports: 
            - 3000:3000
        command: bash -c "cd /backend && npm update && npm install negotiator && npm install media-typer && npm install && node app"
    frontend: 
        image: nginx:1.13
        volumes: 
            - C:\Users\Marco\Documents\Git\docker-lab\5-compose\frontend:/usr/share/nginx/html/
        ports:
            - 8080:80
    